builds:
- id: ocireg-mcp
  dir: .
  main: ./cmd/server
  ldflags:
  - -X main.version={{.Env.VERSION}}
  labels:
    org.opencontainers.image.created: "{{.Env.CREATION_TIME}}"
    org.opencontainers.image.description: "OCI Registry MCP Server"
    org.opencontainers.image.licenses: "MIT"
    org.opencontainers.image.revision: "{{.Env.GITHUB_SHA}}"
    org.opencontainers.image.source: "{{.Env.GITHUB_SERVER_URL}}/{{.Env.GITHUB_REPOSITORY}}"
    org.opencontainers.image.title: "ocireg-mcp"
    org.opencontainers.image.url: "{{.Env.GITHUB_SERVER_URL}}/{{.Env.GITHUB_REPOSITORY}}"
    org.opencontainers.image.version: "{{.Env.VERSION}}"