version: '3'

vars:
  BINARY_NAME: ocireg-mcp
  BUILD_DIR: build
  MAIN_PACKAGE: ./cmd/server

tasks:
  default:
    desc: Run tests and build the application
    deps: [test, build]

  build:
    desc: Build the application
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}} {{.MAIN_PACKAGE}}

  run:
    desc: Run the application
    deps: [build]
    cmds:
      - ./{{.BUILD_DIR}}/{{.BINARY_NAME}}

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  clean:
    desc: Clean the build directory
    cmds:
      - rm -rf {{.BUILD_DIR}}

  fmt:
    desc: Format the code
    cmds:
      - go fmt ./...
      - golangci-lint run --fix

  lint:
    desc: Lint the code
    cmds:
      - golangci-lint run

  deps:
    desc: Update dependencies
    cmds:
      - go mod tidy

  install:
    desc: Install dependencies
    cmds:
      - go mod download

  docker-build:
    desc: Build container image locally using ko
    cmds:
      - ko build --local --base-import-paths {{.MAIN_PACKAGE}}
    env:
      KO_DOCKER_REPO: '{{.KO_DOCKER_REPO | default "ko.local/ocireg-mcp"}}'
      VERSION: '{{.VERSION | default "dev"}}'
      CREATION_TIME: '{{now | date "2006-01-02T15:04:05Z07:00"}}'

  docker-build-multiarch:
    desc: Build multi-architecture container image using ko
    cmds:
      - ko build --local --platform=linux/amd64,linux/arm64 --base-import-paths {{.MAIN_PACKAGE}}
    env:
      KO_DOCKER_REPO: '{{.KO_DOCKER_REPO | default "ko.local/ocireg-mcp"}}'
      VERSION: '{{.VERSION | default "dev"}}'
      CREATION_TIME: '{{now | date "2006-01-02T15:04:05Z07:00"}}'